// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_8Mk-e8UrcrG5lIUwVOte_iW_YMoEqm4',
    appId: '1:539127475744:android:6deb6ddbfdea9a6e05d645',
    messagingSenderId: '539127475744',
    projectId: 'attendance-app-2759d',
    storageBucket: 'attendance-app-2759d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4upzT8wJD2yH4FBj7xKYn5mVGjiyOj4A',
    appId: '1:539127475744:ios:71b7fcffea46613205d645',
    messagingSenderId: '539127475744',
    projectId: 'attendance-app-2759d',
    storageBucket: 'attendance-app-2759d.firebasestorage.app',
    // androidClientId: '943779324095-t82gtue83s5auek0j20d1q6pf9i9gae7.apps.googleusercontent.com',
    // iosClientId: '943779324095-iavb4huhln8eo2nl0gc4qf84har8d5mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp',
  );

}